### ISSUE TITLE
Figure out way to embed HTML in org files

### ISSUE THREAD

**Issue by StevenTammen** [StevenTammen/steventammen.com#15]
- https://github.com/chaseadamsio/goorgeous/issues/19
- Use markdown files temporarily to embed things like forms when necessary.
- Probably not worth making table of contents work 100% correctly with the markdown files (it doesn't at the moment). Want to get HTML in Org instead.

**Comment by kaushalmodi** [comment]
Hello, I'm a stranger from internet, randomly happened to come across these Org + Hugo issues. I am the developer of the `ox-hugo` Emacs package that exports Org files to Hugo-friendly Markdown files + front-matter. You might want to see if that meets your needs...

https://ox-hugo.scripter.co/ <- Package website exported from Org using `ox-hugo`, and generated using Hugo

**Comment by StevenTammen** [comment]
Wow, thanks for stopping by haha.

I'd come across your project (and your comments related to the Goorgeous project), but it seems to me to make more sense to just implement things in the Org parser directly (and skip the Markdown step). At least as an eventual goal for the long-term.

With the parsers as fast as they are, I take it that there is not a big performance hit in using the extra markdown step? One of the things I like about my current workflow is that when I save the file and switch to my browser, the page is already reloaded on localhost:1313/. 

If there isn't much delay added, maybe I'll give this a whirl, and try to fix some of Goorgeous' shortcomings if/when I learn Go. Support for nested lists is the other big issue I have with Goorgeous.

**Comment by kaushalmodi** [comment]
> it seems to me to make more sense to just implement things in the Org parser directly (and skip the Markdown step). At least as an eventual goal for the long-term.

Of course, I went down the path of `ox-hugo` once I realized that it would be impossible to do things in Goorgeous that I take for granted in Org.. One basic thing would be supporting the Org export options using `#+options:` keyword, and exporting each sub-tree as a separate post so that stuff like tags, etc. get inherited so that you don't need to type the front-matter manually in each new post.

> I take it that there is not a big performance hit in using the extra markdown step?

It definitely is a huge performance hit if you choose to export all the Org posts to Markdown each time you publish the site. The benefit becomes very apparent when you *amortize* that net performance hit.. **you export only the post you are working on**, and then commit the exported Markdown file. When you are focusing on editing just one post, the Org export step delay is insignificant.. so much so that I hit `C-x C-s` in my Org buffer, and by the time I glance to the side to my browser.. the whole Org -(ox-hugo)-> Markdown -(Hugo)-> HTML translation would have finished :)

See https://ox-hugo.scripter.co/doc/auto-export-on-saving/.

**Comment by StevenTammen** [comment]
Cool. Thanks for the further clarification.

Do you keep a separate markdown directory in `hugo-dir/content/posts`, for example, or store your org files and markdown files in the same place? Do you track your Org files using Git, with the benefits therein, or just the markdown files? (I'd want my Org files under version control in the commits).

Also, aren't archetypes designed for avoiding typing out metadata? Currently, when I run something like `hugo new posts/somepost.org`, I automatically get a YAML metadata block, and only have to fill in categories/tags (my taxonomies).

**Comment by kaushalmodi** [comment]
> Do you keep a separate markdown directory in hugo-dir/content/posts

I have to keep the Org source separate from Markdown directory, else Hugo will try to parse them.

So while the content for Hugo is usually in `content/`, I keep the Org source in `content-org/`.. it can be actually any directory that Hugo doesn't read by default.

> Do you track your Org files using Git

Of course.. I track both Org + Markdown.

You can find my site source here: https://ox-hugo.scripter.co/doc/examples/ (See the row with `scripter.co`).

> Also, aren't archetypes designed for avoiding typing out metadata?

Sounds like a bit of boasting, but `ox-hugo` obsoletes archetypes.. (if you pick the subtree-based flow). I have deleted the archetypes dir from my site.

> only have to fill in categories/tags (my taxonomies).

You don't have to do even that.. (if you pick the subtree-based flow).

See this:

```org
* My Emacs posts :emacs:
** Post 1
```

By inheritance, *Post 1* gets the `emacs` tag... Tomorrow if I have:

```org
* My Emacs posts :emacs:
** Post 1
** Post 2
```

*Post 2* gets that `emacs` tag too, by inheritance.

You can nest the tags and categories in interesting ways.. you can look at my *scripter.co* site source or the `ox-hugo` tests in `all-posts.org`. The latter source is linked in that above examples page too.
